version: '3'

services: 
    mongo:
        container_name: ms_mongo 
        image: mongo:latest
        ports: 
            - "27017:27017"
        volumes: 
            - "./mongo/db:/data/db"
    nginx: 
        image: nginx:1.15
        container_name: ms_nginx
        depends_on: 
            - users
            - posts
        ports: 
            - "80:80"
        volumes: 
             - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    eureka-server:
        image: quickbooks2018/eureka-server
        container_name: ms_eurekaserver
        hostname: eureka-server
        ports:
            - "8761:8761"
    users: 
        build: ./users
        container_name: ms_users
        depends_on:
            - "rabbitmq"
            - "mongo"
            - "eureka-server"
        volumes: 
            - "./users:/src/app"
        working_dir: "/src/app"
        ports: 
            - "3200:3200"
        command: "npm run start"
    posts: 
        build: ./posts
        container_name: ms_posts
        depends_on:
            - "rabbitmq" 
            - "mongo"
        volumes: 
            - "./posts:/src/app"
        working_dir: "/src/app"
        ports: 
            - "3000:3000"
        command: npm run start
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes: 
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq