version: '3'

services: 
    mongo:
        container_name: ms_mongo 
        image: mongo:latest
        ports: 
            - "27017:27017"
        volumes: 
            - "./mongo/db:/data/db"
    nginx: 
        image: nginx:1.15
        container_name: ms_nginx
        depends_on: 
            - users
            - posts
        ports: 
            - "80:80"
        volumes: 
             - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    users: 
        build: ./users
        container_name: ms_users
        depends_on: 
            - "mongo"
        volumes: 
            - "./users:/src/app"
        working_dir: "/src/app"
        ports: 
            - "3200:3200"
        command: "npm run start"
    posts: 
        build: ./posts
        container_name: ms_posts
        depends_on: 
            - "mongo"
        volumes: 
            - "./posts:/src/app"
        working_dir: "/src/app"
        ports: 
            - "3000:3000"
        command: npm run start